In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_rows = 1000

df_red = pd.read_csv("winequality-red.csv", sep=';')
df_white = pd.read_csv("winequality-white.csv", sep=';')
df_white

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [2]:
df_red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
x_red = df_red.drop('quality', axis=1)
y_red = df_red['quality']
x_white = df_white.drop('quality', axis=1)
y_white = df_white['quality']

In [49]:
from sklearn.model_selection import train_test_split
x_red_train, x_red_test, y_red_train, y_red_test = train_test_split(x_red, y_red, random_state=42, train_size=0.7)
x_white_train, x_white_test, y_white_train, y_white_test = train_test_split(x_white, y_white, random_state=42, train_size=0.7)

/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
model = RandomForestClassifier(random_state=42,
                               # опции, относящиеся к отдельным деревьям такаие же, как в tree.DecisionTreeClassifier
                               # число деревьев в лесу
                               n_estimators=20,
                               # функция для impurity ('gini' или 'entropy')
                               criterion='entropy',
                               max_depth=10,
                               # Вычислять out-of-bag ошибку
                               oob_score=True,
                               # использовать результаты предыдущего вызова и нарастить предыдущий лес 
                               warm_start=False,
                               # веса классов для балансировки обучения
                               class_weight=None,#"balanced",
                               max_features="sqrt"
                              )
model.fit(x_red_train, y_red_train)
y_red_pred = model.predict(x_red_test)
print('Accuracy score:\t',metrics.accuracy_score(y_red_pred, y_red_test),'\n')
print(metrics.classification_report(y_red_pred, y_red_test))

Accuracy score:	 0.65

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.76      0.70      0.73       212
           6       0.66      0.61      0.64       215
           7       0.49      0.58      0.53        52
           8       0.17      1.00      0.29         1

   micro avg       0.65      0.65      0.65       480
   macro avg       0.35      0.48      0.36       480
weighted avg       0.69      0.65      0.67       480

/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

In [51]:
pd.DataFrame({'feature': x_red.columns,
              'importance': model.feature_importances_}).sort_values('importance', ascending=False)

                 feature  importance
10               alcohol    0.169386
9              sulphates    0.126703
1       volatile acidity    0.107003
7                density    0.098732
6   total sulfur dioxide    0.094058
4              chlorides    0.079233
2            citric acid    0.072151
0          fixed acidity    0.070793
3         residual sugar    0.063669
8                     pH    0.059228
5    free sulfur dioxide    0.059044

In [52]:
print('Out-of-bag:\t',model.oob_score_)

Out-of-bag:	 0.6041108132260947

In [53]:
model.fit(x_white_train, y_white_train)
y_white_pred = model.predict(x_white_test)
print('Accuracy score:\t',metrics.accuracy_score(y_white_pred, y_white_test),'\n')
print(metrics.classification_report(y_white_pred,y_white_test))

Accuracy score:	 0.6258503401360545

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.15      0.75      0.25         8
           5       0.68      0.65      0.66       447
           6       0.74      0.60      0.66       814
           7       0.44      0.65      0.53       191
           8       0.18      0.90      0.31        10

   micro avg       0.63      0.63      0.63      1470
   macro avg       0.37      0.59      0.40      1470
weighted avg       0.67      0.63      0.64      1470

/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

In [54]:
pd.DataFrame({'feature': x_white.columns,
              'importance': model.feature_importances_}).sort_values('importance', ascending=False)

                 feature  importance
10               alcohol    0.134211
7                density    0.120599
1       volatile acidity    0.109728
5    free sulfur dioxide    0.105416
6   total sulfur dioxide    0.085780
4              chlorides    0.081297
3         residual sugar    0.081294
8                     pH    0.075080
2            citric acid    0.071455
9              sulphates    0.070551
0          fixed acidity    0.064589

In [55]:
print(model.oob_score_)

0.6070595099183197

In [56]:
df = pd.concat([df_red, df_white], ignore_index=True)
x = pd.concat([x_red, x_white], ignore_index=True)
y = pd.concat([y_red, y_white], ignore_index=True)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, train_size=0.7)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('Accuracy score:\t',metrics.accuracy_score(y_pred, y_test),'\n')
print(metrics.classification_report(y_pred,y_test))

/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

Accuracy score:	 0.6210256410256411

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.06      0.67      0.11         6
           5       0.70      0.62      0.66       697
           6       0.71      0.62      0.66      1025
           7       0.42      0.62      0.50       214
           8       0.16      1.00      0.28         8
           9       0.00      0.00      0.00         0

   micro avg       0.62      0.62      0.62      1950
   macro avg       0.29      0.50      0.32      1950
weighted avg       0.67      0.62      0.64      1950

/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
/Users/yasen/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)